[package]
name = "rsnano_rpc_messages"
version = "0.1.0"
edition = "2021"

[dependencies]
rsnano_core = { path = "../core" }
rsnano_node = { path = "../node" }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.72"
