[package]
name = "rsnano-insight"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29.1"
egui_extras = "0.29.1"
rsnano_core = { path = "../../core" }
rsnano_messages = { path = "../../messages" }
rsnano_network = { path = "../../network" }
rsnano_store_lmdb = { path = "../../store_lmdb" }
rsnano_node = { path = "../../node" }
rsnano_ledger = { path = "../../ledger" }
rsnano_nullable_clock = { path = "../../nullables/clock" }
tokio = { version = "1", features = ["rt-multi-thread"] }
num-format = "0.4.4"
num = "0"
num-traits = "0"
num-derive = "0"
chrono = "0.4.19"
