[package]
name = "rsnano_store_lmdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
output_tracking = []

[dev-dependencies]
rsnano_store_lmdb = { path = ".", features = ["output_tracking"] }

[dependencies]
rsnano_core = { path = "../core" }
rsnano_output_tracker = { path = "../nullables/output_tracker" }
rsnano_nullable_lmdb = { path = "../nullables/lmdb" }
lmdb-rkv = "0.14"
lmdb-rkv-sys = "0.11"
primitive-types = "0"
anyhow = "1"
uuid = { version = "0", features = ["v4"] }
num-traits = "0"
rand = { version = "0" }
num-derive = "0"
serde_json = "1"
tracing = "0.1"
serde = { version = "1", features = ["derive"] }
